site_name: ORCD Docs
site_url: https://orcd.mit.edu
nav:
  - Home: index.md

#theme: readthedocs
theme: 
  name: material
  logo: images/ORCD_logo_icononly.png
  features:
    - content.code.copy
  palette:
    primary: blue grey
markdown_extensions:
    - toc:
        permalink: 
plugins:
  - search
#  - tags:
#      tags_file: tags.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
