name: build

on:
  push:
    branches:
    - main
        
jobs:
  buildpages:
    runs-on:  ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      
      - name: install
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -r requirements.txt
          
      - name: add_path
        run: |
          echo "/home/runner/.local/bin" >> $GITHUB_PATH
          
      - name: build
        run: |
          make html
          touch _build/html/.nojekyll
          ls -altr _build/html
          
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PRODUCTION_WEB_PAGE_DEPLOY }}
          
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.PRODUCTION_WEB_PAGE_DEPLOY }}
          SSH: true 
          BRANCH: main # The branch the action should deploy to.
          FOLDER: _build/html # The folder the action should deploy.
          CLEAN: false # Automatically remove deleted files from the deploy branch
          REPOSITORY_NAME: XXXXXXXXXXXXXXXXXXXX
          ACCESS_TOKEN: ${{ secrets.PRODUCTION_WEB_PAGE_DEPLOY }}
          TARGET_FOLDER: docs  
