on: 
    pull_request:
         types:
           - opened
           - synchronize

jobs:
  buildprstep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -r requirements.txt
          
      - name: add_path
        run: |
          echo "/home/runner/.local/bin" >> $GITHUB_PATH

      - name: build
        run: |
          make html
          touch _build/html/.nojekyll
          ls -altr _build/html

      - name: show-pull-number
        run: |
          echo "github.event.number" = ${{ github.event.number }}

      - name: create-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}_PR${{ github.event.number }}_preview-artifact
          path: /home/runner/work/orcd-docs-edit/orcd-docs-edit/_build/html/
          
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.PREVIEW_WEB_PAGE_DEPLOY }}
          SSH: true 
          BRANCH: main # The branch the action should deploy to.
          FOLDER: _build/html # The folder the action should deploy.
          CLEAN: false # Automatically remove deleted files from the deploy branch
          REPOSITORY_NAME: mit-orcd/orcd-docs-previews
          ACCESS_TOKEN: ${{ secrets.PREVIEW_WEB_PAGE_DEPLOY }}
          TARGET_FOLDER: PR/PR${{ github.event.number }}


